;======================================================================
; VPTEST.APP
; Creates a test harness for the virtual machine & virtual machine
; extensions.
;======================================================================

;ROM layout:
;0000 - 07ff   monitor page 0
;0800 - 0fff   monitor page 1
;1000 - 17ff   virtual processor
;1800 - 1fff   virtual processor extensions
;2000 - 27ff   finite state machine

:;******************************************************************
:;*                       vmtestgn.asm                             *
:;* Autogenerated file for testing ROBOT VIRTUAL MACHINE           *
:;*                                                                *
:;******************************************************************

:;******************************************************************
:; Variables for monitor, fsm & VM processor
:;******************************************************************
include ..\Variables.asm

:;******************************************************************
:; Entry points for monitor
:;******************************************************************
include monjmp.asm

:;******************************************************************
:; Test code
:            .org  4100h                 ; user space
include vmtest.asm

; VIRTPROC now in EPROM
;:
;:;********************* ROBOT VIRTUAL MACHINE **********************
;:            .org  4800h                 ; start on next 2k page
;include ..\Virtproc.asm

; VMSUPPORT now in EPROM
;:
;:;********************* ROBOT VM EXTENSIONS **********************
;:            .org 5000h   ; 			 ; start on next 2k page
;include ..\VMSupport.asm


:
:
:;******************************  END  *******************************
:.end
output  vmtestgn.asm
run     a51 vmtestgn.asm


